version: "3"
services:
  egpt: 
    image: anton666/snack-small-talk
    container_name: snack-small-talk-core
    ports:
      - 8085:8085
    volumes:
      - ./files:/files
    environment:
      - SPRING_PROFILES_ACTIVE=PROM
      - STUB_ENABLED=false
      - STUB_FILE=./files/tts_stub
      - ASR_ENDPOINT=http://localhost:8000
      - GPT_ENDPOINT=http://localhost:8001
      - TTS_ENDPOINT=http://localhost:8002
    restart: unless-stopped