chat:
  stub:
    enabled: ${STUB_ENABLED}
    file: ${STUB_FILE}
  services:
    asr:
      endpoint: ${ASR_ENDPOINT}
    gpt:
      endpoint: ${GPT_ENDPOINT}
    tts:
      endpoint: ${TTS_ENDPOINT}
